export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const CHANGE_ITEM_STATUS = 'CHANGE_ITEM_STATUS';
export const SHOW_ALL_ITEMS = 'SHOW_ALL_ITEMS';
export const SHOW_COMPLITED_ITEMS = 'SHOW_COMPLITED_ITEMS';
export const SHOW_ACTIVE_ITEMS = 'SHOW_ACTIVE_ITEMS';
